import { expect } from 'chai'
import { _createTestDatapackage, _repoExists } from '../commonTestFunctions'
import {
  getFileBlobsAndPaths,
  createLfsFiles,
} from '../../src/backend/githubApiHelper'
import datapackage from '../fixtures/datapackage.json'

const lfs_test_server = 'http://some-local-server'
const sampleMetadata = {
  name: 'Test Package',
  resources: [
    {
      path: 'data/myresource.csv',
      hash: '0f1128046248f83dc9b9ab187e16fad0ff596128f1524d05a9a77c4ad932f10a',
      bytes: 1234,
    },
    {
      path: 'data/newResource.csv',
      hash: '0f1128046248f83dc9b9ab187e16fad0ff596128f1524d05a9a77c4ad932f11b',
      bytes: 14,
    },
  ],
}

const files = {
  metadata: sampleMetadata,
  readMe: `'# ¯\\_(ツ)_/¯\n'
    'This is a datapackage repository created by '
    '[\`metastore-lib\`](https://github.com/datopian/metastore-lib)'`,
}

describe('LFS Helpers-getFileBlobsAndPaths', () => {
  it('Test getFileBlobsAndPaths for package with resource', () => {
    const blobs = getFileBlobsAndPaths(files, lfs_test_server)
    const expectedBlobOutput = [
      'ewogICJuYW1lIjogIlRlc3QgUGFja2FnZSIsCiAgInJlc291cmNlcyI6IFsKICAgIHsKICAgICAgInBhdGgiOiAiZGF0YS9teXJlc291cmNlLmNzdiIsCiAgICAgICJoYXNoIjogIjBmMTEyODA0NjI0OGY4M2RjOWI5YWIxODdlMTZmYWQwZmY1OTYxMjhmMTUyNGQwNWE5YTc3YzRhZDkzMmYxMGEiLAogICAgICAiYnl0ZXMiOiAxMjM0CiAgICB9LAogICAgewogICAgICAicGF0aCI6ICJkYXRhL25ld1Jlc291cmNlLmNzdiIsCiAgICAgICJoYXNoIjogIjBmMTEyODA0NjI0OGY4M2RjOWI5YWIxODdlMTZmYWQwZmY1OTYxMjhmMTUyNGQwNWE5YTc3YzRhZDkzMmYxMWIiLAogICAgICAiYnl0ZXMiOiAxNAogICAgfQogIF0KfQ==',
      'ZGF0YS9teXJlc291cmNlLmNzdiBmaWx0ZXI9bGZzIGRpZmY9bGZzIG1lcmdlPWxmcyAtdGV4dApkYXRhL25ld1Jlc291cmNlLmNzdiBmaWx0ZXI9bGZzIGRpZmY9bGZzIG1lcmdlPWxmcyAtdGV4dAo=',
      'W3JlbW90ZSAib3JpZ2luIl0KCWxmc3VybCA9IGh0dHA6Ly9zb21lLWxvY2FsLXNlcnZlcg==',
      'JyMgwq9cXyjjg4QpXy/CrwonCiAgICAnVGhpcyBpcyBhIGRhdGFwYWNrYWdlIHJlcG9zaXRvcnkgY3JlYXRlZCBieSAnCiAgICAnW2BtZXRhc3RvcmUtbGliYF0oaHR0cHM6Ly9naXRodWIuY29tL2RhdG9waWFuL21ldGFzdG9yZS1saWIpJw==',
      'dmVyc2lvbiBodHRwczovL2dpdC1sZnMuZ2l0aHViLmNvbS9zcGVjL3YxCm9pZCBzaGEyNTY6MGYxMTI4MDQ2MjQ4ZjgzZGM5YjlhYjE4N2UxNmZhZDBmZjU5NjEyOGYxNTI0ZDA1YTlhNzdjNGFkOTMyZjEwYQpzaXplIDEyMzQK',
      'dmVyc2lvbiBodHRwczovL2dpdC1sZnMuZ2l0aHViLmNvbS9zcGVjL3YxCm9pZCBzaGEyNTY6MGYxMTI4MDQ2MjQ4ZjgzZGM5YjlhYjE4N2UxNmZhZDBmZjU5NjEyOGYxNTI0ZDA1YTlhNzdjNGFkOTMyZjExYgpzaXplIDE0Cg==',
    ]
    const expectedBlobPaths = [
      'datapackage.json',
      '.gitattributes',
      '.lfsconfig',
      'README.md',
      'data/myresource.csv',
      'data/newResource.csv',
    ]

    expect(blobs.filesAsUTF8).to.eql(expectedBlobOutput)
    expect(blobs.pathsForUTF8Files).to.eql(expectedBlobPaths)
  })

  it('Test getFileBlobsAndPaths for package without resource', () => {
    const files = {
      metadata: {
        name: 'Test Package',
        resources: [],
      },
      readMe: `'# ¯\\_(ツ)_/¯\n'
          'This is a datapackage repository created by '
          '[\`metastore-lib\`](https://github.com/datopian/metastore-lib)'`,
    }
    const blobs = getFileBlobsAndPaths(files, lfs_test_server)
    const expectedBlobOutput = [
      'ewogICJuYW1lIjogIlRlc3QgUGFja2FnZSIsCiAgInJlc291cmNlcyI6IFtdCn0=',
      'JyMgwq9cXyjjg4QpXy/CrwonCiAgICAgICAgICAnVGhpcyBpcyBhIGRhdGFwYWNrYWdlIHJlcG9zaXRvcnkgY3JlYXRlZCBieSAnCiAgICAgICAgICAnW2BtZXRhc3RvcmUtbGliYF0oaHR0cHM6Ly9naXRodWIuY29tL2RhdG9waWFuL21ldGFzdG9yZS1saWIpJw==',
    ]
    const expectedBlobPaths = ['datapackage.json', 'README.md']

    expect(blobs.filesAsUTF8).to.eql(expectedBlobOutput)
    expect(blobs.pathsForUTF8Files).to.eql(expectedBlobPaths)
  })

  it('Returns empty array when path is not available in resource', () => {
    const result = createLfsFiles(datapackage, 'http://localhost:3000')
    expect(result).to.eql([])
  })

  it('Test getFileBlobsAndPaths for datapacke without resource path', () => {
    const files = {
      metadata: datapackage,
      readMe: `'# ¯\\_(ツ)_/¯\n'
          'This is a datapackage repository created by '
          '[\`metastore-lib\`](https://github.com/datopian/metastore-lib)'`,
    }
    const blobs = getFileBlobsAndPaths(files, lfs_test_server)
    const expectedBlobOutput = [
      'ewogICJAY29udGV4dCI6ICJodHRwOi8vc2NoZW1hcy5mcmljdGlvbmxlc3NkYXRhLmlvL2Zpc2NhbC1kYXRhLXBhY2thZ2UuanNvbmxkIiwKICAiYXV0aG9yIjogIiIsCiAgImRlc2NyaXB0aW9uIjogIiIsCiAgIm1vZGVsIjogewogICAgImRpbWVuc2lvbnMiOiB7CiAgICAgICJhY3Rpdml0eSI6IHsKICAgICAgICAiZGltZW5zaW9uVHlwZSI6ICJhY3Rpdml0eSIsCiAgICAgICAgInByaW1hcnlLZXkiOiBbCiAgICAgICAgICAicmVzaWR1YWxfc3VnYXIiCiAgICAgICAgXSwKICAgICAgICAiYXR0cmlidXRlcyI6IHsKICAgICAgICAgICJ0eXBlIjogewogICAgICAgICAgICAic291cmNlIjogInR5cGUiLAogICAgICAgICAgICAidGl0bGUiOiAidHlwZSIKICAgICAgICAgIH0sCiAgICAgICAgICAiZml4ZWRfYWNpZGl0eSI6IHsKICAgICAgICAgICAgInNvdXJjZSI6ICJmaXhlZCBhY2lkaXR5IiwKICAgICAgICAgICAgInRpdGxlIjogImZpeGVkIGFjaWRpdHkiCiAgICAgICAgICB9LAogICAgICAgICAgInZvbGF0aWxlX2FjaWRpdHkiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAidm9sYXRpbGUgYWNpZGl0eSIsCiAgICAgICAgICAgICJ0aXRsZSI6ICJ2b2xhdGlsZSBhY2lkaXR5IgogICAgICAgICAgfSwKICAgICAgICAgICJjaXRyaWNfYWNpZCI6IHsKICAgICAgICAgICAgInNvdXJjZSI6ICJjaXRyaWMgYWNpZCIsCiAgICAgICAgICAgICJ0aXRsZSI6ICJjaXRyaWMgYWNpZCIKICAgICAgICAgIH0sCiAgICAgICAgICAicmVzaWR1YWxfc3VnYXIiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAicmVzaWR1YWwgc3VnYXIiLAogICAgICAgICAgICAidGl0bGUiOiAicmVzaWR1YWwgc3VnYXIiCiAgICAgICAgICB9LAogICAgICAgICAgImNobG9yaWRlcyI6IHsKICAgICAgICAgICAgInNvdXJjZSI6ICJjaGxvcmlkZXMiLAogICAgICAgICAgICAidGl0bGUiOiAiY2hsb3JpZGVzIgogICAgICAgICAgfSwKICAgICAgICAgICJmcmVlX3N1bGZ1cl9kaW94aWRlIjogewogICAgICAgICAgICAic291cmNlIjogImZyZWUgc3VsZnVyIGRpb3hpZGUiLAogICAgICAgICAgICAidGl0bGUiOiAiZnJlZSBzdWxmdXIgZGlveGlkZSIKICAgICAgICAgIH0sCiAgICAgICAgICAidG90YWxfc3VsZnVyX2Rpb3hpZGUiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAidG90YWwgc3VsZnVyIGRpb3hpZGUiLAogICAgICAgICAgICAidGl0bGUiOiAiZCIKICAgICAgICAgIH0sCiAgICAgICAgICAiZGVuc2l0eSI6IHsKICAgICAgICAgICAgInNvdXJjZSI6ICJkZW5zaXR5IiwKICAgICAgICAgICAgInRpdGxlIjogImRlbnNpdHkiCiAgICAgICAgICB9LAogICAgICAgICAgInF1YWxpdHkiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAicXVhbGl0eSIsCiAgICAgICAgICAgICJ0aXRsZSI6ICJxdWFsaXR5IgogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfSwKICAgICAgImFkbWluaXN0cmF0aXZlLWNsYXNzaWZpY2F0aW9uIjogewogICAgICAgICJkaW1lbnNpb25UeXBlIjogImNsYXNzaWZpY2F0aW9uIiwKICAgICAgICAicHJpbWFyeUtleSI6IFsKICAgICAgICAgICJwSCIsCiAgICAgICAgICAic3VscGhhdGVzIiwKICAgICAgICAgICJhbGNvaG9sIgogICAgICAgIF0sCiAgICAgICAgImF0dHJpYnV0ZXMiOiB7CiAgICAgICAgICAicEgiOiB7CiAgICAgICAgICAgICJzb3VyY2UiOiAicEgiLAogICAgICAgICAgICAidGl0bGUiOiAicEgiCiAgICAgICAgICB9LAogICAgICAgICAgInN1bHBoYXRlcyI6IHsKICAgICAgICAgICAgInNvdXJjZSI6ICJzdWxwaGF0ZXMiLAogICAgICAgICAgICAidGl0bGUiOiAic3VscGhhdGVzIgogICAgICAgICAgfSwKICAgICAgICAgICJhbGNvaG9sIjogewogICAgICAgICAgICAic291cmNlIjogImFsY29ob2wiLAogICAgICAgICAgICAidGl0bGUiOiAiYWxjb2hvbCIKICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJjbGFzc2lmaWNhdGlvblR5cGUiOiAiYWRtaW5pc3RyYXRpdmUiCiAgICAgIH0KICAgIH0sCiAgICAibWVhc3VyZXMiOiB7fQogIH0sCiAgIm5hbWUiOiAid2luZXF1YWxpdHlOLmNzdiIsCiAgInByb2ZpbGUiOiAiZGF0YS1wYWNrYWdlIiwKICAidGl0bGUiOiAid2luZXF1YWxpdHlOLmNzdiIsCiAgInJlc291cmNlcyI6IFsKICAgIHsKICAgICAgImJ5dGVzIjogMzkwMzc2LAogICAgICAiaGFzaCI6ICJjYjAxZjkxYzcwZGUwNjZmODVkNGNmZmFjM2JiMTYzZTQ3MTk1MjM4NjFjZDc5YmE4ODI1YjcyMmNmOThiNDhjIiwKICAgICAgImZvcm1hdCI6ICJjc3YiLAogICAgICAic2NoZW1hIjogewogICAgICAgICJmaWVsZHMiOiB7CiAgICAgICAgICAidHlwZSI6IHsKICAgICAgICAgICAgInRpdGxlIjogInR5cGUiLAogICAgICAgICAgICAibmFtZSI6ICJ0eXBlIiwKICAgICAgICAgICAgInNsdWciOiAidHlwZSIsCiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICJmb3JtYXQiOiAiZGVmYXVsdCIsCiAgICAgICAgICAgICJjb2x1bW5UeXBlIjogImFjdGl2aXR5OmdlbmVyaWM6Y29udHJhY3Q6bGFiZWwiLAogICAgICAgICAgICAiY29uY2VwdFR5cGUiOiAiYWN0aXZpdHkiLAogICAgICAgICAgICAib3B0aW9ucyI6IFtdCiAgICAgICAgICB9LAogICAgICAgICAgImZpeGVkIGFjaWRpdHkiOiB7CiAgICAgICAgICAgICJ0aXRsZSI6ICJmaXhlZCBhY2lkaXR5IiwKICAgICAgICAgICAgIm5hbWUiOiAiZml4ZWQgYWNpZGl0eSIsCiAgICAgICAgICAgICJzbHVnIjogImZpeGVkX2FjaWRpdHkiLAogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgICAiZm9ybWF0IjogImRlZmF1bHQiLAogICAgICAgICAgICAiY29sdW1uVHlwZSI6ICJhY3Rpdml0eTpnZW5lcmljOmNvbnRyYWN0OmxhYmVsIiwKICAgICAgICAgICAgImNvbmNlcHRUeXBlIjogImFjdGl2aXR5IiwKICAgICAgICAgICAgIm9wdGlvbnMiOiBbXQogICAgICAgICAgfSwKICAgICAgICAgICJ2b2xhdGlsZSBhY2lkaXR5IjogewogICAgICAgICAgICAidGl0bGUiOiAidm9sYXRpbGUgYWNpZGl0eSIsCiAgICAgICAgICAgICJuYW1lIjogInZvbGF0aWxlIGFjaWRpdHkiLAogICAgICAgICAgICAic2x1ZyI6ICJ2b2xhdGlsZV9hY2lkaXR5IiwKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICAgImZvcm1hdCI6ICJkZWZhdWx0IiwKICAgICAgICAgICAgImNvbHVtblR5cGUiOiAiYWN0aXZpdHk6Z2VuZXJpYzpjb250cmFjdDpsYWJlbCIsCiAgICAgICAgICAgICJjb25jZXB0VHlwZSI6ICJhY3Rpdml0eSIsCiAgICAgICAgICAgICJvcHRpb25zIjogW10KICAgICAgICAgIH0sCiAgICAgICAgICAiY2l0cmljIGFjaWQiOiB7CiAgICAgICAgICAgICJ0aXRsZSI6ICJjaXRyaWMgYWNpZCIsCiAgICAgICAgICAgICJuYW1lIjogImNpdHJpYyBhY2lkIiwKICAgICAgICAgICAgInNsdWciOiAiY2l0cmljX2FjaWQiLAogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgICAiZm9ybWF0IjogImRlZmF1bHQiLAogICAgICAgICAgICAiY29sdW1uVHlwZSI6ICJhY3Rpdml0eTpnZW5lcmljOmNvbnRyYWN0OmxhYmVsIiwKICAgICAgICAgICAgImNvbmNlcHRUeXBlIjogImFjdGl2aXR5IiwKICAgICAgICAgICAgIm9wdGlvbnMiOiBbXQogICAgICAgICAgfSwKICAgICAgICAgICJyZXNpZHVhbCBzdWdhciI6IHsKICAgICAgICAgICAgInRpdGxlIjogInJlc2lkdWFsIHN1Z2FyIiwKICAgICAgICAgICAgIm5hbWUiOiAicmVzaWR1YWwgc3VnYXIiLAogICAgICAgICAgICAic2x1ZyI6ICJyZXNpZHVhbF9zdWdhciIsCiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICJmb3JtYXQiOiAiZGVmYXVsdCIsCiAgICAgICAgICAgICJjb2x1bW5UeXBlIjogImFjdGl2aXR5OmdlbmVyaWM6cHJvZ3JhbTpjb2RlIiwKICAgICAgICAgICAgImNvbmNlcHRUeXBlIjogImFjdGl2aXR5IiwKICAgICAgICAgICAgIm9wdGlvbnMiOiBbXQogICAgICAgICAgfSwKICAgICAgICAgICJjaGxvcmlkZXMiOiB7CiAgICAgICAgICAgICJ0aXRsZSI6ICJjaGxvcmlkZXMiLAogICAgICAgICAgICAibmFtZSI6ICJjaGxvcmlkZXMiLAogICAgICAgICAgICAic2x1ZyI6ICJjaGxvcmlkZXMiLAogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgICAiZm9ybWF0IjogImRlZmF1bHQiLAogICAgICAgICAgICAiY29sdW1uVHlwZSI6ICJhY3Rpdml0eTpnZW5lcmljOmNvbnRyYWN0OmxhYmVsIiwKICAgICAgICAgICAgImNvbmNlcHRUeXBlIjogImFjdGl2aXR5IiwKICAgICAgICAgICAgIm9wdGlvbnMiOiBbXQogICAgICAgICAgfSwKICAgICAgICAgICJmcmVlIHN1bGZ1ciBkaW94aWRlIjogewogICAgICAgICAgICAidGl0bGUiOiAiZnJlZSBzdWxmdXIgZGlveGlkZSIsCiAgICAgICAgICAgICJuYW1lIjogImZyZWUgc3VsZnVyIGRpb3hpZGUiLAogICAgICAgICAgICAic2x1ZyI6ICJmcmVlX3N1bGZ1cl9kaW94aWRlIiwKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICAgImZvcm1hdCI6ICJkZWZhdWx0IiwKICAgICAgICAgICAgImNvbHVtblR5cGUiOiAiYWN0aXZpdHk6Z2VuZXJpYzpjb250cmFjdDpsYWJlbCIsCiAgICAgICAgICAgICJjb25jZXB0VHlwZSI6ICJhY3Rpdml0eSIsCiAgICAgICAgICAgICJvcHRpb25zIjogW10KICAgICAgICAgIH0sCiAgICAgICAgICAidG90YWwgc3VsZnVyIGRpb3hpZGUiOiB7CiAgICAgICAgICAgICJ0aXRsZSI6ICJkIiwKICAgICAgICAgICAgIm5hbWUiOiAidG90YWwgc3VsZnVyIGRpb3hpZGUiLAogICAgICAgICAgICAic2x1ZyI6ICJ0b3RhbF9zdWxmdXJfZGlveGlkZSIsCiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICJmb3JtYXQiOiAiZGVmYXVsdCIsCiAgICAgICAgICAgICJjb2x1bW5UeXBlIjogImFjdGl2aXR5OmdlbmVyaWM6Y29udHJhY3Q6bGFiZWwiLAogICAgICAgICAgICAiY29uY2VwdFR5cGUiOiAiYWN0aXZpdHkiLAogICAgICAgICAgICAib3B0aW9ucyI6IFtdCiAgICAgICAgICB9LAogICAgICAgICAgImRlbnNpdHkiOiB7CiAgICAgICAgICAgICJ0aXRsZSI6ICJkZW5zaXR5IiwKICAgICAgICAgICAgIm5hbWUiOiAiZGVuc2l0eSIsCiAgICAgICAgICAgICJzbHVnIjogImRlbnNpdHkiLAogICAgICAgICAgICAidHlwZSI6ICJzdHJpbmciLAogICAgICAgICAgICAiZm9ybWF0IjogImRlZmF1bHQiLAogICAgICAgICAgICAiY29sdW1uVHlwZSI6ICJhY3Rpdml0eTpnZW5lcmljOmNvbnRyYWN0OmxhYmVsIiwKICAgICAgICAgICAgImNvbmNlcHRUeXBlIjogImFjdGl2aXR5IiwKICAgICAgICAgICAgIm9wdGlvbnMiOiBbXQogICAgICAgICAgfSwKICAgICAgICAgICJwSCI6IHsKICAgICAgICAgICAgInRpdGxlIjogInBIIiwKICAgICAgICAgICAgIm5hbWUiOiAicEgiLAogICAgICAgICAgICAic2x1ZyI6ICJwSCIsCiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICJmb3JtYXQiOiAiZGVmYXVsdCIsCiAgICAgICAgICAgICJjb2x1bW5UeXBlIjogImFkbWluaXN0cmF0aXZlLWNsYXNzaWZpY2F0aW9uOmdlbmVyaWM6Y29kZSIsCiAgICAgICAgICAgICJjb25jZXB0VHlwZSI6ICJhZG1pbmlzdHJhdGl2ZS1jbGFzc2lmaWNhdGlvbiIsCiAgICAgICAgICAgICJvcHRpb25zIjogW10KICAgICAgICAgIH0sCiAgICAgICAgICAic3VscGhhdGVzIjogewogICAgICAgICAgICAidGl0bGUiOiAic3VscGhhdGVzIiwKICAgICAgICAgICAgIm5hbWUiOiAic3VscGhhdGVzIiwKICAgICAgICAgICAgInNsdWciOiAic3VscGhhdGVzIiwKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICAgImZvcm1hdCI6ICJkZWZhdWx0IiwKICAgICAgICAgICAgImNvbHVtblR5cGUiOiAiYWRtaW5pc3RyYXRpdmUtY2xhc3NpZmljYXRpb246Z2VuZXJpYzpsZXZlbDI6Y29kZSIsCiAgICAgICAgICAgICJjb25jZXB0VHlwZSI6ICJhZG1pbmlzdHJhdGl2ZS1jbGFzc2lmaWNhdGlvbiIsCiAgICAgICAgICAgICJvcHRpb25zIjogW10KICAgICAgICAgIH0sCiAgICAgICAgICAiYWxjb2hvbCI6IHsKICAgICAgICAgICAgInRpdGxlIjogImFsY29ob2wiLAogICAgICAgICAgICAibmFtZSI6ICJhbGNvaG9sIiwKICAgICAgICAgICAgInNsdWciOiAiYWxjb2hvbCIsCiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICJmb3JtYXQiOiAiZGVmYXVsdCIsCiAgICAgICAgICAgICJjb2x1bW5UeXBlIjogImFkbWluaXN0cmF0aXZlLWNsYXNzaWZpY2F0aW9uOmdlbmVyaWM6Y29kZSIsCiAgICAgICAgICAgICJjb25jZXB0VHlwZSI6ICJhZG1pbmlzdHJhdGl2ZS1jbGFzc2lmaWNhdGlvbiIsCiAgICAgICAgICAgICJvcHRpb25zIjogW10KICAgICAgICAgIH0sCiAgICAgICAgICAicXVhbGl0eSI6IHsKICAgICAgICAgICAgInRpdGxlIjogInF1YWxpdHkiLAogICAgICAgICAgICAibmFtZSI6ICJxdWFsaXR5IiwKICAgICAgICAgICAgInNsdWciOiAicXVhbGl0eSIsCiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICJmb3JtYXQiOiAiZGVmYXVsdCIsCiAgICAgICAgICAgICJjb2x1bW5UeXBlIjogImFjdGl2aXR5OmdlbmVyaWM6Y29udHJhY3Q6bGFiZWwiLAogICAgICAgICAgICAiY29uY2VwdFR5cGUiOiAiYWN0aXZpdHkiLAogICAgICAgICAgICAib3B0aW9ucyI6IFtdCiAgICAgICAgICB9CiAgICAgICAgfSwKICAgICAgICAicHJpbWFyeUtleSI6IFsKICAgICAgICAgICJyZXNpZHVhbCBzdWdhciIsCiAgICAgICAgICAicEgiLAogICAgICAgICAgInN1bHBoYXRlcyIsCiAgICAgICAgICAiYWxjb2hvbCIKICAgICAgICBdCiAgICAgIH0sCiAgICAgICJlbmNvZGluZyI6ICJ1dGYtOCIsCiAgICAgICJtZWRpYXR5cGUiOiAidGV4dC9jc3YiLAogICAgICAibmFtZSI6ICJ3aW5lcXVhbGl0eU4uY3N2IiwKICAgICAgImRpYWxlY3QiOiB7CiAgICAgICAgImRlbGltaXRlciI6ICIsIiwKICAgICAgICAicXVvdGVDaGFyIjogIlwiIgogICAgICB9CiAgICB9CiAgXQp9',
      'JyMgwq9cXyjjg4QpXy/CrwonCiAgICAgICAgICAnVGhpcyBpcyBhIGRhdGFwYWNrYWdlIHJlcG9zaXRvcnkgY3JlYXRlZCBieSAnCiAgICAgICAgICAnW2BtZXRhc3RvcmUtbGliYF0oaHR0cHM6Ly9naXRodWIuY29tL2RhdG9waWFuL21ldGFzdG9yZS1saWIpJw==',
    ]
    const expectedBlobPaths = ['datapackage.json', 'README.md']

    expect(blobs.filesAsUTF8).to.eql(expectedBlobOutput)
    expect(blobs.pathsForUTF8Files).to.eql(expectedBlobPaths)
  })
})
